### PR TITLE
fix doubles of cited documents on page back

### LINKED ISSUE #2561: Duplicate bibliographies listed after using back button
1. Go to https://parker.stanford.edu/parker/catalog/94257JYP
2. Under "This reference is found in these document bibliographies" click on "Cambridge, Corpus Christi College, MS 293: William Langland, Piers Plowman"
3. Go back to the original page using the back button
4. Notice duplicate link added for "Cambridge, Corpus Christi College, MS 293: William Langland, Piers Plowman"
5. Repeating steps 2 & 3 results in another entry each time

Image

### PR DESCRIPTION
**Pull request by dnoneill**
closes #2561

### CODE REVIEW

File: app/assets/javascripts/cited_documents.js [hunk 1]
```diff
@@ -8,6 +8,9 @@
   CitedDocuments = {
     init: function (el) {
       var $el = $(el);
+      const citedDocList = $el.find('.cited-documents-list');
+      if (citedDocList[0].innerHTML != '') return;
```
Comment (jcoyne) [inline app/assets/javascripts/cited_documents.js:12]: Can you add a comment to the code about why we're bailing out here and in which situations this happens?

Comment (dnoneill) [reply app/assets/javascripts/cited_documents.js:13]: Done

**Review by jcoyne — APPROVED** [review]
