### PR TITLE
limit size of error messages when saving to database

### LINKED ISSUE #709: [exhibits/stage] ActiveRecord::StatementInvalid: Mysql2::Error: Got a packet bigger than 'max_allowed_packet'
## Backtrace

    line 6 of [PROJECT_ROOT]/app/jobs/record_index_status_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/34896431)

[exhibits/stage] ActiveRecord::StatementInvalid: Mysql2::Error: Got a packet bigger than 'max_allowed_packet' bytes: UPDATE `spotlight_solr_document_sidecars` SET `index_status` = x'2d2d2d0a3a6f6b3a2066616c73650a3a6d6573736167653a207c2d0a2020233c52536f6c723a3a4572726f723a3a487474703a2052536f6c723a3a4572726f723a3a48747470202d203430302042616420526571756573740a20204572726f723a207b22726573706f6e7365486561646572223a7b22737461747573223a3430302c225154696d65223a313732347d2c226572726f72223a7b226d65746164617461223...

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #709, or at least fixes the buffer overflow issue.

### CODE REVIEW

File: app/models/dor_harvester.rb [hunk 1]
```diff
@@ -1,3 +1,5 @@
+include ActionView::Helpers::TextHelper
```
Comment (cbeer) [inline app/models/dor_harvester.rb]: 👎 to including this helper globally.

File: app/models/dor_harvester.rb [hunk 2]
```diff
@@ -64,8 +66,10 @@ def on_error(resource, exception_or_message)
               else
                 exception_or_message.to_s
               end
-
-    RecordIndexStatusJob.perform_later(self, resource.bare_druid, ok: false, message: message)
+    RecordIndexStatusJob.perform_later(self,
+                                       resource.bare_druid,
+                                       ok: false,
+                                       message: truncate(message, limit: 1.megabyte))
```
Comment (cbeer) [inline app/models/dor_harvester.rb]: Actually, Rails makes `String#truncate` available, so we shouldn't need `TextHelper` at all.

**Comment by drh-stanford** [comment]
Great, thanks for the feedback. I didn't know about `String#truncate`. I've updated the PR
