### PR TITLE
make sure iiif drag and drop has aria-label

### LINKED ISSUE #2483: Unique links should have unique, meaningful text
### Current behavior

There are multiple unique IIIF Drag-n-drop links without unique, meaningful text. This could make it difficult to understand their behavior when navigating by screen reader. See [WCAG SC 2.4.4 Link Purpose (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context).

iiif-links

### Steps to reproduce

Example page (/catalog): [Parker Library - Search Results](https://exhibits.stanford.edu/parker/catalog?f%5Bformat_main_ssim%5D%5B%5D=Archive%2FManuscript&search_field=manuscript_number&sort=title_sort+asc%2C+pub_year_isi+desc).

### Possible solution

WCAG Level A: [Understanding Success Criterion 2.4.4: Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context).

See SODA's recommendations below.

### Reported by SODA

> Violation: Ensure link text is meaningful within context
> Severity: Major
> 
> [Issue]
> There are link elements that do not have meaningful text. There are multiple A element with an accessible name of 'iiif drag-n-drop' that is the same as another A element but doesn't go to the same HREF.
> 
> [User Impact]
> Without meaningful text, screen reader users who navigate the page or navigate using a list of links (provided by their Assistive Technology, e.g., JAWS, VoiceOver, etc...) will not be able to discern the purpose of these links.
> 
> [Code Reference]
> ```
> <div class="col-2 col-md-1">
>   <a class="iiif-dnd float-right" data-turbolinks="false" href=...">
>     IIIF Drag-n-drop
>   </a>
> </div>
> ```
> [Recommendation]
> Developers must ensure that links have meaningful text within context. This can be achieved by changing the ALT text or by using an aria-label, aria-labelledby to provide link purpose in context.
> 
> [ALT Text Example]
> ```
> <div class="col-2 col-md-1">
>   <a class="iiif-dnd float-right" data-turbolinks="false" href=...">
>     IIIF Drag-n-drop: Cambridge, Corpus Christi College, MS 002I: The Bury Bible
>   </a>
> </div>
> ```
> [ARIA-LABEL Example]
> ```
> <div class="col-2 col-md-1">
>   <a class="iiif-dnd float-right" data-turbolinks="false" href=..." aria-label=" Cambridge, Corpus Christi College, MS 002I: The Bury Bible">
>     IIIF Drag-n-drop
>   </a>
> </div>
> ```
> [ARIA-LABELLEDBY Example]
> ```
> <h3 id="titleMs002I">Cambridge, Corpus Christi College, MS 002I: The Bury Bible</h3>
> <div class="col-2 col-md-1">
>   <a class="iiif-dnd float-right" data-turbolinks="false" href=..." id="linkMs002I" aria-labelledby="linkMs002I titleMs002I">
>     IIIF Drag-n-drop
>   </a>
> </div>
> ```

### PR DESCRIPTION
**Pull request by dnoneill**
closes #2483

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -18,9 +18,10 @@ def document_leaflet_map(document:, **)
 
   ##
   # @param [String] manifest
-  def iiif_drag_n_drop(manifest, width: '40')
+  def iiif_drag_n_drop(manifest, width: '40', document: nil)
     link_url = format Settings.iiif_dnd_base_url, query: { manifest: manifest }.to_query
-    link_to link_url, class: 'iiif-dnd float-right', data: { turbolinks: false } do
+    link_to link_url, class: 'iiif-dnd float-right', data: { turbolinks: false },
+                      aria: { label: document['title_display'] } do
```
Comment (jcoyne) [inline app/helpers/application_helper.rb:24]: Shouldn't this be something like "Drag to a IIIF viewer to open \"#{document['title_display']}\"" ?

Comment (dnoneill) [reply app/helpers/application_helper.rb:24]: The ticket indicates no? ```<div class="col-2 col-md-1">
  <a class="iiif-dnd float-right" data-turbolinks="false" href=..." aria-label=" Cambridge, Corpus Christi College, MS 002I: The Bury Bible">
    IIIF Drag-n-drop
  </a>
</div>
```

Comment (dnoneill) [reply app/helpers/application_helper.rb]: @jcoyne I talked with Alan. We have updated the aria label to include drag-n-drop and made the alt text empty.

**Review by jcoyne — APPROVED** [review]
