### PR TITLE
Fix up javascript dependencies for bootstrap 4

### LINKED ISSUE #1481: BL7 update: Address Popper.js error (sort & per page dropdowns)
`TypeError: Bootstrap's dropdowns require Popper.js`

### PR DESCRIPTION
**Pull request by cbeer**
Fixes  #1481

### CODE REVIEW

File: app/assets/javascripts/index_status_typeahead.js [hunk 1]
```diff
@@ -15,6 +15,7 @@
     },
 
     init: function (el) {
+      console.log('!!!');
```
Comment (mejackreed) [inline app/assets/javascripts/index_status_typeahead.js]: cruft?

Comment (cbeer) [reply app/assets/javascripts/index_status_typeahead.js]: Vitally important code!
